# Default values for k8s-landing-page.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "k8s-landing-page"
fullnameOverride: "k8s-landing-page"

image:
  repository: ghcr.io/catenax-ng/k8s-helm-example
  pullPolicy: Always
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

replicaCount: 1

autoscaling:
  enabled: false

ingress:
  enabled: false
  annotations:
    # -- Ingress class to use
    kubernetes.io/ingress.class: nginx
    # -- Ensure SSL redirect
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # -- SSL termination will be handled by ingress instead of ingress controller
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # -- The backend protokoll of the ingress
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    # -- FQDN for the ingress
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    # -- FQDN for the TLS ingress
    - hosts:
        - ""
      # -- k8s secret containing the TLS cert
      secretName: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

# -- Following Catena-X Helm Best Practices # Ref: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000

service:
  # -- Specifies the Catenax-ng environment (e.g. "DEV", "INT", "PRE-PROD")
  environment: ""
  type: ClusterIP
  # -- Default port exposed of used container image
  port: 8080

# -- Following Catena-X Helm Best Practices # Ref: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

# -- Affinity and anti-affinity rules for server scheduling to nodes
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
#
# Following Catena-X Helm Best Practices: https://catenax-ng.github.io/docs/kubernetes-basics/helm
affinity: {}
  # # An example of preferred pod anti-affinity, weight is in the range 1-100
  # podAntiAffinity:
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #     - weight: 100
  #       podAffinityTerm:
  #         labelSelector:
  #           matchExpressions:
  #             - key: app.kubernetes.io/name
  #               operator: DoesNotExist
  #         topologyKey: kubernetes.io/hostname

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L210
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
