apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-landing-page.fullname" . }}
  labels:
    {{- include "k8s-landing-page.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-landing-page.selectorLabels" . | nindent 4 }}
