<<<<<<< HEAD
name: check for conventional commits
=======
name: commit linting
>>>>>>> 689e4dc496672d6ec07ec123b2fd085c48a553dd

on: 
  pull_request:

jobs:
<<<<<<< HEAD
  commit-lint-on-pr:
    name: check linting
=======
  commit-lint:
    name: commit linting
>>>>>>> 689e4dc496672d6ec07ec123b2fd085c48a553dd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: install commitlint
        run: npm install --save-dev @commitlint/{cli,config-conventional}
      - name: lint commit messages
        run: npx commitlint --from HEAD~1 --verbose